### ISSUE TITLE
Error when packaging a function

### ISSUE THREAD

**Issue by florianib** [pbiernat/ripr#11] opened 2017-11-21 18:20 UTC
Hey, I love your plugin, though it fails to package a little function. 
![untitled](https://user-images.githubusercontent.com/21081469/33089407-c805bfba-cef0-11e7-9dc0-e0e9a66a558c.png)
![untitled2](https://user-images.githubusercontent.com/21081469/33089409-cb1e9e7e-cef0-11e7-8e9d-754885bb43d8.png)

The file is from an old CTF, and the function was CRC32 I think.
Here is the binary if you want to take a look at it: [D17.zip](https://github.com/pbiernat/ripr/files/1492487/D17.zip)

Any idea why it fails?

**Comment by pbiernat** [comment] 2017-11-21 20:22
Hey, thanks for the bug report and testcase!

The root cause of this is that the Binary Ninja `get_function_at()` API is platform-specific, and so does not "see" a function at this address. This is because this function is `thumb2` code, but the BinaryView binja gives to ripr has its platform defaulted to `arm7`.

I'll refactor things a bit tonight to make sure ripr accounts for this scenario.

**Comment by florianib** [comment] 2017-11-21 21:27
Cool thank you very much!
Sorry to hijack this thread now, but I tried your plugin with some other CTF challenges:

1) Another ARM challenge, where a byte array gets run through some function (called magic) and your input has to match this value. I get another error that an 'int' object is not iterable:
[Errors1.zip](https://github.com/pbiernat/ripr/files/1492980/Errors1.zip)
[ARMme_12.zip](https://github.com/pbiernat/ripr/files/1492981/ARMme_12.zip)


2) A Windows x86 application, which is a more advanced key-gen challenge. The Windows functions in BinaryNinja are named like that: "DllName!FunctionName". When your plugin exports them into python, function names like this get created: 
`def hook_KERNEL32!GetModuleHandleA(self): pass`

    But **!** characters are not allowed in function names in python, hence I get an error and cannot run the script. Also if I remove the illegal characters I cannot run the exported class, because I get an "Invalid memory mapping error"

    > Traceback (most recent call last):
  File "C:/Users/x/Desktop/test2.py", line 43, in <module>
    x = test2()
  File "C:/Users/x/Desktop/test2.py", line 19, in __init__
    self.mu.mem_map(0x404000L,0x4000)
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 407, in mem_map
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory mapping (UC_ERR_MAP)
    
    [D21.zip](https://github.com/pbiernat/ripr/files/1493017/D21.zip)


Do you know what's up with these errors?

Keep up the good work :) Let me know if I can help you somehow!

EDIT:  <del>Okey I may have fixed the invalid memory mapping error. In Windows you need to run it as an administrator (in my case pycharm), else it fails.</del> Okey false positive, I still get the error

**Comment by florianib** [comment] 2017-12-06 15:53
Hey, sorry to bother you, but did you make any progress?

**Comment by bkerler** [comment] 2018-08-23 08:02
On Nr. 2: That happens if data1 is mapped at the wrong section. Use page option instead or comment out data1 (or any other data section causing the issue)

**Comment by bkerler** [comment] 2018-08-23 18:55
Sorted out both code examples and pushed fixes :)

**Closed as completed** 2022-08-11 18:47 UTC
